// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jynklrscgeshapzrogfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5bmtscnNjZ2VzaGFwenJvZ2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjE0NTYsImV4cCI6MjA3MDY5NzQ1Nn0.Erc_w4exzWUdtt0WXDbqwcFiJgPvAVWrYQYjj4s8ld0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});